export default [
  {
    displayName: "Bitcoin",
    dataName: "bitcoin",
    color: "green",
    price: 66282.72,
    change: "2.43%",
  },
  {
    displayName: "Ethereum",
    dataName: "ethereum",
    color: "green",
    price: 2435.82,
    change: "2.43%",
  },
  {
    displayName: "Ripple",
    dataName: "ripple",
    color: "red",
    price: 3331.83,
    change: "2.43%",
  },
  {
    displayName: "Shiba",
    dataName: "shiba",
    color: "green",
    price: 434.85,
    change: "2.43%",
  },
  {
    displayName: "Cardano",
    dataName: "cardano",
    color: "red",
    price: 66289.63,
    change: "2.43%",
  },
  {
    displayName: "Tether",
    dataName: "tether",
    color: "green",
    price: 11832.0,
    change: "2.43%",
  },
  {
    displayName: "Litecoin",
    dataName: "litecoin",
    color: "red",
    price: 2282.76,
    change: "2.43%",
  },
  {
    displayName: "Polkadot",
    dataName: "polkadot",
    color: "red",
    price: 7275.48,
    change: "2.43%",
  },
  {
    displayName: "Solana",
    dataName: "solana",
    color: "green",
    price: 2814.22,
    change: "2.43%",
  },
];
